In [4]:
conda install numpy


Solving environment: done

# All requested packages already installed.


Note: you may need to restart the kernel to use updated packages.


In [23]:
import numpy as np

arr1=np.arange(0,25)

print(arr1,"\n")

print(arr1.shape,"\n")

print(arr1.reshape(5,5),"\n")


print(np.arange(0,20).reshape(4,5),"\n")

print(np.arange(0,20).reshape(4,-1))

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24] 

(25,) 

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]] 

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]] 

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]
