In [4]:
conda install numpy


Solving environment: done

# All requested packages already installed.


Note: you may need to restart the kernel to use updated packages.


In [1]:
import numpy as np

arr1=np.arange(0,25)

print(arr1,"\n")

print(arr1.shape,"\n")

print(arr1.reshape(5,5),"\n")


print(np.arange(0,20).reshape(4,5),"\n")

print(np.arange(0,20).reshape(4,-1))

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24] 

(25,) 

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]] 

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]] 

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]


In [34]:
(np.random.rand(10).cumsum())

array([0.71616021, 1.04488012, 1.07823965, 1.21502878, 2.18858734,
       2.48830066, 3.42779772, 3.97867265, 4.46434674, 5.3715559 ])

In [40]:
0.71616021+0.86104374

1.57720395

In [3]:
arr1= np.

SyntaxError: invalid syntax (4101659114.py, line 1)

In [47]:
arr1.cumsum()

array([0.98062556, 1.58573124, 1.71169247, 2.32320208, 3.2626321 ,
       3.47432458, 4.22913001, 4.72581305, 5.45988337, 6.01700268])

In [7]:
import numpy as np

#Creating array using list
list1=[10,2,3,9,5,7,8]
arr1=np.array(list1)
print(arr1)

#creating array using tuple
tup1=2,3,4,6,7,8,2
arr2=np.array(tup1)
print(arr2)


#creating array using arrange

arr3=np.arange(25)
print(arr3)
print(np.arange(1,10))
print(np.arange(1,100,5))

[10  2  3  9  5  7  8]
[2 3 4 6 7 8 2]
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24]
[1 2 3 4 5 6 7 8 9]
[ 1  6 11 16 21 26 31 36 41 46 51 56 61 66 71 76 81 86 91 96]


In [11]:
#Creating multi dimensional array using arange function

arr1=np.arange(10,30).reshape(5,4)
print(arr1)
arr2=np.arange(10,30).reshape(5,-1)
arr2

[[10 11 12 13]
 [14 15 16 17]
 [18 19 20 21]
 [22 23 24 25]
 [26 27 28 29]]


array([[10, 11, 12, 13],
       [14, 15, 16, 17],
       [18, 19, 20, 21],
       [22, 23, 24, 25],
       [26, 27, 28, 29]])

In [46]:
# creating multi dimensional array using multi list

list1=[20,40,50,60]

arr1=np.array(list1).reshape(2,-1)
print(arr1)

list2=[23,4,5,4]

arr2=np.array((list1,list2))
arr2

[[20 40]
 [50 60]]


array([[20, 40, 50, 60],
       [23,  4,  5,  4]])

In [27]:
# linspace :returns the random elemnts of given two numbers
# if step is not given it gives defalut of 50 values

arr1=np.linspace(5,10)

print(arr1)

print(np.linspace(5,10,20))

[ 5.          5.10204082  5.20408163  5.30612245  5.40816327  5.51020408
  5.6122449   5.71428571  5.81632653  5.91836735  6.02040816  6.12244898
  6.2244898   6.32653061  6.42857143  6.53061224  6.63265306  6.73469388
  6.83673469  6.93877551  7.04081633  7.14285714  7.24489796  7.34693878
  7.44897959  7.55102041  7.65306122  7.75510204  7.85714286  7.95918367
  8.06122449  8.16326531  8.26530612  8.36734694  8.46938776  8.57142857
  8.67346939  8.7755102   8.87755102  8.97959184  9.08163265  9.18367347
  9.28571429  9.3877551   9.48979592  9.59183673  9.69387755  9.79591837
  9.89795918 10.        ]
[ 5.          5.26315789  5.52631579  5.78947368  6.05263158  6.31578947
  6.57894737  6.84210526  7.10526316  7.36842105  7.63157895  7.89473684
  8.15789474  8.42105263  8.68421053  8.94736842  9.21052632  9.47368421
  9.73684211 10.        ]


In [36]:
# to create arrays of zeros

print(np.zeros(10))
print(np.zeros(10).reshape(5,2))

# to create arrays of ones

print(np.ones(12))
print(np.ones(12,dtype=int).reshape(4,3))


[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[[0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]]
[1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
[[1 1 1]
 [1 1 1]
 [1 1 1]
 [1 1 1]]


In [38]:
# to create identity matrix

arr1=np.eye(4)
print(arr1)

print(np.identity(5,dtype=int))

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]
[[1 0 0 0 0]
 [0 1 0 0 0]
 [0 0 1 0 0]
 [0 0 0 1 0]
 [0 0 0 0 1]]


In [59]:
# to create empty array

empt_arr=np.empty((4,2)) #creates array with some random values  of given matrix or value
print(empt_arr)

# to create random array

print(np.random.rand(10),"\n") # creates array with random values between 0 and 1

print(np.random.rand(20).cumsum()) # creates array with random values and do cumulative sum b/w 0 and 1

[[0.00000000e+000 6.79038654e-313]
 [6.79038654e-313 2.22809558e-312]
 [2.14321575e-312 2.46151512e-312]
 [2.41907520e-312 5.97819431e-322]]
[0.39403402 0.51574598 0.2577767  0.29165336 0.63407466 0.1391684
 0.5552332  0.23027963 0.03847482 0.28548202] 

[ 0.69333987  1.49495378  2.34484012  3.25411555  3.3887626   4.2121169
  4.23321276  5.0469272   5.84079837  6.61136066  6.71024203  6.85645336
  7.54490028  7.83011757  8.23639668  8.48893694  9.32266287  9.87592409
 10.36233185 10.95817664]


In [67]:
# to show more values in array

# before
print(np.arange(2000))

import sys

np.set_printoptions(threshold=sys.maxsize)

#after
print(np.arange(2000))

[   0    1    2 ... 1997 1998 1999]
[   0    1    2    3    4    5    6    7    8    9   10   11   12   13
   14   15   16   17   18   19   20   21   22   23   24   25   26   27
   28   29   30   31   32   33   34   35   36   37   38   39   40   41
   42   43   44   45   46   47   48   49   50   51   52   53   54   55
   56   57   58   59   60   61   62   63   64   65   66   67   68   69
   70   71   72   73   74   75   76   77   78   79   80   81   82   83
   84   85   86   87   88   89   90   91   92   93   94   95   96   97
   98   99  100  101  102  103  104  105  106  107  108  109  110  111
  112  113  114  115  116  117  118  119  120  121  122  123  124  125
  126  127  128  129  130  131  132  133  134  135  136  137  138  139
  140  141  142  143  144  145  146  147  148  149  150  151  152  153
  154  155  156  157  158  159  160  161  162  163  164  165  166  167
  168  169  170  171  172  173  174  175  176  177  178  179  180  181
  182  183  184  185  186  187  188  189 

# Reshaping an array

In [88]:
# before
arr1=np.arange(12)
print(arr1.shape)

# after
arr2=np.arange(12).reshape(4,3)
print(arr2.shape)

arr2=np.arange(12).reshape(3,-1) #also works with -1
print(arr2.shape)

# to interchange rows and colums
print(arr2.shape)

arr2.resize(4,3)

print(arr2.shape)

arr3=np.arange(12).reshape(3,-1).T
print(arr3.shape)


(12,)
(4, 3)
(3, 4)
(3, 4)
(4, 3)
(4, 3)


In [97]:
# row major format

arr3= np.arange(20)
print(arr3)
print(np.reshape(arr3,(4,5),order='C'))

# column major format

np.reshape(arr3,(4,5),order='F')

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]


array([[ 0,  4,  8, 12, 16],
       [ 1,  5,  9, 13, 17],
       [ 2,  6, 10, 14, 18],
       [ 3,  7, 11, 15, 19]])

# Basic Operations

In [8]:
arr1=np.arange(0,5)

print(f"original array : { arr1}\n")
print(f"original array : { arr1} and add operation{arr1+2}\n")
print(f"original array : { arr1} and sub operation{arr1-2}\n")
print(f"original array : { arr1} and multi operation{arr1*2}\n")
print(f"original array : { arr1} and multi operation{arr1/2}\n")
print(f"original array : { arr1} and floor operation{arr1//2}\n")
print(f"original array : { arr1} and mod operation{arr1%2}\n")
print(f"original array : { arr1} and pow operation{arr1**2}\n")

original array : [0 1 2 3 4]

original array : [0 1 2 3 4] and add operation[2 3 4 5 6]

original array : [0 1 2 3 4] and sub operation[-2 -1  0  1  2]

original array : [0 1 2 3 4] and multi operation[0 2 4 6 8]

original array : [0 1 2 3 4] and multi operation[0.  0.5 1.  1.5 2. ]

original array : [0 1 2 3 4] and floor operation[0 0 1 1 2]

original array : [0 1 2 3 4] and mod operation[0 1 0 1 0]

original array : [0 1 2 3 4] and pow operation[ 0  1  4  9 16]



# Comparison operations

In [17]:
arr1=np.arange(10)
print(f"original array : { arr1}\n")

print(arr1>5)

print(arr1[arr1>5])

bol_array=arr1<4
print(bol_array)
print(arr1[arr1<4])


original array : [0 1 2 3 4 5 6 7 8 9]

[False False False False False False  True  True  True  True]
[6 7 8 9]
[ True  True  True  True False False False False False False]
[0 1 2 3]


# Unary Operations

In [30]:
arr1=np.array([2,6,4,7,9])

print(f"original array : { arr1}\n")
print(f"sqrt function : {np.sqrt(arr1)}\n")
print(f"log function : {np.log(arr1)}\n")

print(f"sin function : {np.sin(arr1)}\n")

# to get sin values in radian

print(f"sin function : {np.sin(arr1 * np.pi/180)}\n")
print(f"cos function : {np.cos(arr1 * np.pi/180)}\n")
print(f"arcsin(inverse sin) function : {np.arcsin(arr1 * np.pi/180)}\n")
print(f"arctan(inverse cos) function : {np.arctan(arr1 * np.pi/180)}\n")


original array : [2 6 4 7 9]

sqrt function : [1.41421356 2.44948974 2.         2.64575131 3.        ]

log function : [0.69314718 1.79175947 1.38629436 1.94591015 2.19722458]

sin function : [ 0.90929743 -0.2794155  -0.7568025   0.6569866   0.41211849]

sin function : [0.0348995  0.10452846 0.06975647 0.12186934 0.15643447]

cos function : [0.99939083 0.9945219  0.99756405 0.99254615 0.98768834]

arcsin(inverse sin) function : [0.03491368 0.1049121  0.06987    0.12247904 0.15773288]

arctan(inverse cos) function : [0.03489242 0.10433946 0.06970008 0.12157057 0.1558065 ]



In [3]:
# Scalar matrix multiplication

arr1=np.arange(9).reshape(3,3)

arr2=np.arange(9).reshape(3,3)
print(arr1,"\n")
print(arr2,"\n")
print(f"Scalar matrix :\n {arr1*arr2}")

dot=np.dot(arr1,arr2)

print(f"Vector matrix: \n{dot}")
arr1.dot(arr2)

[[0 1 2]
 [3 4 5]
 [6 7 8]] 

[[0 1 2]
 [3 4 5]
 [6 7 8]] 

Scalar matrix :
 [[ 0  1  4]
 [ 9 16 25]
 [36 49 64]]
Vector matrix: 
[[ 15  18  21]
 [ 42  54  66]
 [ 69  90 111]]


array([[ 15,  18,  21],
       [ 42,  54,  66],
       [ 69,  90, 111]])

In [17]:
# sum

print(f"sum function: {np.sum(arr1)}")
print(f"max function: {np.max(arr1)}")
print(f"min function: {np.min(arr1)}")
print(f"mean function: {np.mean(arr1)}")
print(f"median function: {np.median(arr1)}")

arr1.max()
arr1.sum()
arr1.min()
arr1.mean()

sum function: 36
max function: 8
min function: 0
mean function: 4.0
median function: 4.0


4.0

# Universal Functions

In [64]:
import numpy as np

arr1=np.array([1,4,5,2,3])
arr2=np.arange(5)

print("add: ",np.add(10,111))
print("add: ",np.add(arr1,arr2))
print("multiply : ", np.multiply(arr1,arr2)) #Scalar multiplication
print(" Dot : ",np.dot(arr1,arr2))

arr3= np.arange(16).reshape(4,4)

print("square each element: \n",np.square(arr3))
print("Radian of each element : \n",np.radians(arr3))
print("sin of each element : \n",np.sin(arr3))
print("Binary value of scalar num \n :", np.binary_repr(109))

print(arr1,"\n",arr2)

print("Bitwise and function: ",np.bitwise_and(arr1,arr2))
print("Bitwise or function: ",np.bitwise_or(arr1,arr2))
print("Bitwise not function: ",np.bitwise_not(arr1,arr2))


add:  121
add:  [1 5 7 5 7]
multiply :  [ 0  4 10  6 12]
 Dot :  32
square each element: 
 [[  0   1   4   9]
 [ 16  25  36  49]
 [ 64  81 100 121]
 [144 169 196 225]]
Radian of each element : 
 [[0.         0.01745329 0.03490659 0.05235988]
 [0.06981317 0.08726646 0.10471976 0.12217305]
 [0.13962634 0.15707963 0.17453293 0.19198622]
 [0.20943951 0.2268928  0.2443461  0.26179939]]
sin of each element : 
 [[ 0.          0.84147098  0.90929743  0.14112001]
 [-0.7568025  -0.95892427 -0.2794155   0.6569866 ]
 [ 0.98935825  0.41211849 -0.54402111 -0.99999021]
 [-0.53657292  0.42016704  0.99060736  0.65028784]]
Binary value of scalar num 
 : 1101101
[1 4 5 2 3] 
 [0 1 2 3 4]
Bitwise and function:  [0 0 0 2 0]
Bitwise or function:  [1 5 7 3 7]
Bitwise not function:  [-2 -5 -6 -3 -4]


# Statstical Functions

#### mean
#### median
#### standard deviation
#### variance

In [66]:
print(arr1)
print("Sum :",np.sum(arr1))
print("Mean: ",np.mean(arr1)) #sum/count of array
print("Median: ",np.median(arr1)) #in ascending order of count is odd middle element if count is even sum of middle elem/2
print("Mode: more number of repetations in array")
print("Standard deviation(std): ",np.std(arr1))
print("Variance: ",np.var(arr1))

[1 4 5 2 3]
Sum : 15
Mean:  3.0
Median:  3.0
Mode: more number of repetations in array
Standard deviation(std):  1.4142135623730951
Variance:  2.0


# Indexing and slicing

In [95]:
arr1 =np.array([1,5,7,3,75,2,6,8,42,56])

arr2=np.arange(36).reshape(6,6)

print("1d array index :",arr1[2])
print("2d array index for row; ",arr2[2]) # it prints entire row
print("2d array index to get value : ",arr2[2][3])
print("2d array index to get value : ",arr2[2,3])# another way

#Slicing
print("1d array slicing :",arr1[1:4])
print("2d array slicing for row;\n ",arr2[1:3]) #to get only rows
print("2d array slicing for row;\n ",arr2[1:3,2:5]) #to slice rows and colums
print("Length of array:",len(arr1))
print("Length of array:",len(arr2)) #displays how many rows

1d array index : 7
2d array index for row;  [12 13 14 15 16 17]
2d array index to get value :  15
2d array index to get value :  15
1d array slicing : [5 7 3]
2d array slicing for row;
  [[ 6  7  8  9 10 11]
 [12 13 14 15 16 17]]
2d array slicing for row;
  [[ 8  9 10]
 [14 15 16]]
Length of array: 10
Length of array: 6


In [98]:
arr3=np.arange(7)

x=arr3[1],arr3[4],arr3[3],arr3[5],arr3[2] # returns a tuplel
print(x)

index_array=np.array(x)
print("Getting values of array with another array values:",arr1[index_array])

#for two dimensional arrays

second_index_array=np.array([2,4,5,0,5])
print(arr2)

print("Getting values of 2d array with 2 another array values:",arr2[index_array,second_index_array]) #row,column values 

(1, 4, 3, 5, 2)
Getting values of array with another array values: [ 5 75  3  2  7]
[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]
 [24 25 26 27 28 29]
 [30 31 32 33 34 35]]
Getting values of 2d array with 2 another array values: [ 8 28 23 30 17]


In [114]:
print("To get count of non zeros",np.count_nonzero(arr2))
print("To get count of number value more thn given:",np.count_nonzero(arr2>6))
print("To get count of number value more thn given in each row:",np.sum(arr2>6,axis=1))
print("To get count of number value more thn given in each column:",np.sum(arr2>6,axis=0))
print("if any zero is there in matrix:",np.any(arr2))
print("if only all zeros :",np.all(arr2))
print("if all values greater than 5 :",np.all(arr2>5))
print("if any value greater than 5 in matrix :",np.any(arr2>5))

To get count of non zeros 35
To get count of number value more thn given: 29
To get count of number value more thn given in each row: [0 5 6 6 6 6]
To get count of number value more thn given in each column: [4 5 5 5 5 5]
if any zero is there in matrix: True
if only all zeros : False
if all values greater than 5 : False
if any value greater than 5 in matrix : True


# Structured array (Creating custom dtype)

In [8]:
emp_name=['Ram','Bheem','Veera']
emp_sal=[500.56,709.45,105.89]
emp_id=[1001,1002,10003]

cust_dtype=[('name',('U10')),('sal',(np.float64)),('id',(np.int32))]  #('name',(np_str,10))

new_arr=np.zeros(3,dtype=cust_dtype)
print(new_arr)
print('dtpe: ',new_arr.dtype)
print("Adding values")
new_arr['name']=emp_name
new_arr['sal']=emp_sal
new_arr['id']=emp_id

print(new_arr)

[('', 0., 0) ('', 0., 0) ('', 0., 0)]
dtpe:  [('name', '<U10'), ('sal', '<f8'), ('id', '<i4')]
Adding values
[('Ram', 500.56,  1001) ('Bheem', 709.45,  1002) ('Veera', 105.89, 10003)]


# Array Broad casting

In [64]:
# applicable in arithmetic operation of different shape
print("Column Broadcasting")
arr1=np.arange(12).reshape(4,-1)
arr2=np.array([1,2,3])

print(arr2.shape,arr1.shape)   #(5,5)(1,5)
arr3=arr1+arr2
print(arr3,"\n")

print("Row Broadcasting")
arr1=np.arange(12).reshape(4,3)
arr2=np.array([1,2,3,4]).reshape((4,1)) #(5,5)(5,1)

print(arr2.shape,arr1.shape)
arr3=arr1+arr2
print(arr3,"\n")

print("Row & Column Broadcasting")
arr1=np.arange(4)
arr2=np.array([1,2,3,4]).reshape((4,1)) #(5,5)(5,1)


print(arr2.shape,arr1.shape)   #(1,5)(5,1)
arr3=arr1+arr2
print(arr3,"\n")

Column Broadcasting
(3,) (4, 3)
[[ 1  3  5]
 [ 4  6  8]
 [ 7  9 11]
 [10 12 14]] 

Row Broadcasting
(4, 1) (4, 3)
[[ 1  2  3]
 [ 5  6  7]
 [ 9 10 11]
 [13 14 15]] 

Row & Column Broadcasting
(4, 1) (4,)
[[1 2 3 4]
 [2 3 4 5]
 [3 4 5 6]
 [4 5 6 7]] 



# Iterating over an array

In [88]:
#in single dimension

arr1=np.array(['a','c','f','r','t','r'])

for i in arr1:
    print(i)
# In two dimension

print()
arr2=np.arange(12).reshape(4,-1)

for i in arr2:
    print(i)
    for j in i:
        print(j)
#another way with single for
print()
for i in arr2.flatten(): #make 2d array into 1 d array
    print(i)

a
c
f
r
t
r

[0 1 2]
0
1
2
[3 4 5]
3
4
5
[6 7 8]
6
7
8
[ 9 10 11]
9
10
11

0
1
2
3
4
5
6
7
8
9
10
11


# Splitting an array

In [104]:
arr1=np.arange(10)

#splitting into equal parts
a,b=np.split(arr1,2)
print('a: ',a)
print('b: ',b)

#splitting at different position
print(np.split(arr1,[4,7]))

a:  [0 1 2 3 4]
b:  [5 6 7 8 9]
[array([0, 1, 2, 3]), array([4, 5, 6]), array([7, 8, 9])]


In [119]:
#Splitting 2d array
arr2=np.arange(16).reshape(4,-1)

a,b=np.split(arr2,2,axis=1)  
print('a: \n',a)
print('b: \n',b)

arr3=np.arange(30).reshape(5,-1)
print(np.split(arr3,[2,4],axis=0))

a: 
 [[ 0  1]
 [ 4  5]
 [ 8  9]
 [12 13]]
b: 
 [[ 2  3]
 [ 6  7]
 [10 11]
 [14 15]]
[array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11]]), array([[12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23]]), array([[24, 25, 26, 27, 28, 29]])]


In [125]:
#Another way of splitting

print(np.hsplit(arr1,[2,]))
print(np.vsplit(arr3,[2,4]))

[array([0, 1]), array([2, 3, 4, 5, 6, 7, 8, 9])]
[array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11]]), array([[12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23]]), array([[24, 25, 26, 27, 28, 29]])]


# Argsort function

In [7]:
arr1=np.array([2,5,7,3,1,15,10])

print(np.argsort(arr1))
print(arr1)

arr2=arr1[np.argsort(arr1)]
arr2

[4 0 3 1 2 6 5]
[ 2  5  7  3  1 15 10]


array([ 1,  2,  3,  5,  7, 10, 15])

# View and copy

In [16]:
# another way of viewing array as alias

arr1=np.array([1,2,3,4,5])

v1=arr1[2:5]   #alaias

print("Before change")
print(arr1)
print(v1)


arr1[2]=222
print("After change")
print(arr1)
print(v1)
      
      
      
print("\n*********View Function**********\n")
v1=arr1.view()  #Shallow copy

print("Before change")
print(arr1)
print(v1)


arr1[2]=289
print("After change")
print(arr1)
print(v1)

      
      
print("\n*********Copy Function**********\n")
v1=np.copy(arr1) #Deep copy

print("Before change")
print(arr1)
print(v1)


arr1[2]=253
print("After change")
print(arr1)
print(v1)

Before change
[1 2 3 4 5]
[3 4 5]
After change
[  1   2 222   4   5]
[222   4   5]

*********View Function**********

Before change
[  1   2 222   4   5]
[  1   2 222   4   5]
After change
[  1   2 289   4   5]
[  1   2 289   4   5]

*********Copy Function**********

Before change
[  1   2 289   4   5]
[  1   2 289   4   5]
After change
[  1   2 253   4   5]
[  1   2 289   4   5]


# Automatic Reshaping

In [19]:
arr1=np.arange(20)
arr1.shape=4,5  #2d array
arr1

arr1=np.arange(20)
arr1.shape=2,2,5  #3d array
arr1

array([[[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9]],

       [[10, 11, 12, 13, 14],
        [15, 16, 17, 18, 19]]])

# Stacking/Concatination

In [29]:
# Shape of both arrays should be same

arr1=np.arange(6).reshape(3,2)
arr2=np.arange(7,13).reshape(3,2)

arr3=np.concatenate((arr1,arr2))
arr4=np.concatenate((arr1,arr2) ,axis=1) #Vertical Conversion
print(arr3)
print(arr4)


#Stack
arr3=np.vstack((arr1,arr2))
arr4=np.hstack((arr1,arr2)) #Vertical Conversion
print(arr3)
print(arr4)

[[ 0  1]
 [ 2  3]
 [ 4  5]
 [ 7  8]
 [ 9 10]
 [11 12]]
[[ 0  1  7  8]
 [ 2  3  9 10]
 [ 4  5 11 12]]
[[ 0  1]
 [ 2  3]
 [ 4  5]
 [ 7  8]
 [ 9 10]
 [11 12]]
[[ 0  1  7  8]
 [ 2  3  9 10]
 [ 4  5 11 12]]


# Handling csv file in numpy

In [ ]:
# get elements from csv file

# pop_data=np.genfromtxt('Filename.csv',delimiter=',',skip_header=1,usecols=1)

np.argmax(pop_data)#returns max index value
np.argmin(pop_data) #return min index value
np.argsort(pop_data) #sorts array and return indexes in ascending order
np.extract(pop_data>20,pop_data)# returns the satisfying the given condition